<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; line-height: 1.6; padding: 20px; color: #333; }
        .header { border-bottom: 2px solid {{ $primaryColor }}; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { font-size: 22px; margin: 0 0 5px 0; color: {{ $primaryColor }}; }
        .header .meta { font-size: 11px; color: #666; }
        .header .org { font-size: 13px; color: #444; font-weight: bold; }
        h1 { font-size: 20px; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
        h2 { font-size: 16px; margin-top: 20px; color: #444; }
        h3 { font-size: 14px; margin-top: 15px; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        ul, ol { padding-left: 20px; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 10px; color: #999; text-align: center; }
        @if($logoUrl)
        .logo { max-height: 40px; margin-bottom: 5px; }
        @endif
    </style>
</head>
<body>
    <div class="header">
        @if($logoUrl)
            <img src="{{ $logoUrl }}" class="logo" alt="{{ $tenantName }}">
        @endif
        <div class="org">{{ $tenantName }}</div>
        <h1>{{ $meeting->title }}</h1>
        <div class="meta">
            Date: {{ $meeting->ended_at?->format('F j, Y') ?? $meeting->scheduled_at?->format('F j, Y') ?? 'N/A' }}
            &nbsp;|&nbsp; Version: {{ $minutes->version }}
            &nbsp;|&nbsp; Status: {{ ucfirst($minutes->status->value) }}
        </div>
    </div>

    {!! $contentHtml !!}

    <div class="footer">
        Generated by {{ $tenantName }} &mdash; {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
