<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; line-height: 1.4; padding: 15px; color: #333; }
        .header { border-bottom: 2px solid {{ $primaryColor }}; padding-bottom: 10px; margin-bottom: 15px; }
        .header h1 { font-size: 18px; margin: 0 0 5px 0; color: {{ $primaryColor }}; }
        .header .meta { font-size: 10px; color: #666; }
        .header .org { font-size: 12px; color: #444; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th { background-color: {{ $primaryColor }}; color: #fff; padding: 6px 8px; text-align: left; font-size: 10px; text-transform: uppercase; }
        td { border: 1px solid #ddd; padding: 6px 8px; vertical-align: top; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .speaker { font-weight: bold; white-space: nowrap; }
        .agenda-tag { background: #e8f4fd; color: {{ $primaryColor }}; padding: 2px 6px; border-radius: 3px; font-size: 9px; }
        .timestamp { color: #999; font-size: 10px; font-family: monospace; }
        .notes { font-style: italic; color: #666; font-size: 10px; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; text-align: center; }
        @if($logoUrl)
        .logo { max-height: 30px; margin-bottom: 5px; }
        @endif
    </style>
</head>
<body>
    <div class="header">
        @if($logoUrl)
            <img src="{{ $logoUrl }}" class="logo" alt="{{ $tenantName }}">
        @endif
        <div class="org">{{ $tenantName }}</div>
        <h1>Discussion Log: {{ $meeting->title }}</h1>
        <div class="meta">
            Date: {{ $meeting->ended_at?->format('F j, Y') ?? $meeting->scheduled_at?->format('F j, Y') ?? 'N/A' }}
            &nbsp;|&nbsp; Version: {{ $discussionLog->version }}
            &nbsp;|&nbsp; Status: {{ ucfirst($discussionLog->status->value) }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 60px">Time</th>
                <th style="width: 120px">Speaker</th>
                <th>Statement</th>
                <th style="width: 120px">Agenda Item</th>
                <th style="width: 120px">Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
                <tr>
                    <td class="timestamp">
                        @if($entry->timestamp_seconds)
                            {{ gmdate('H:i:s', (int) $entry->timestamp_seconds) }}
                        @endif
                    </td>
                    <td class="speaker">{{ $entry->speaker_name }}</td>
                    <td>{{ $entry->statement }}</td>
                    <td>
                        @if($entry->agendaItem)
                            <span class="agenda-tag">{{ $entry->agendaItem->title }}</span>
                        @endif
                    </td>
                    <td class="notes">{{ $entry->notes }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ $tenantName }} &mdash; {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
